# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='viewings.User'),
            preserve_default=False,
        ),
    ]
