# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0002_office_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
