# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewings', '0003_auto_20160827_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
